name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes: { label: What happened?, placeholder: Clear steps to reproduce... }
    validations: { required: true }
  - type: input
    id: version
    attributes: { label: Package version }
  - type: textarea
    id: extra
    attributes: { label: Extra context }
